import { FacetConfig } from '@sinequa/components/facet';

/**
 * This list is used by Vanilla Search to activate key features in the UI.
 * The order below determines the order of menus, buttons, facets, etc.
 */
export const FEATURES: string[] = [
    "recent-documents",             // Keep track of recently opened documents and suggest them in the autocomplete
    "recent-queries",               // Keep track of recent queries and suggest them in the autocomplete
    "saved-queries",                // Allow users to save queries to easily replay them ang suggest them in the autocomplete
    "baskets",                      // Allow users to bookmark documents in "baskets" (aka "collections") and suggest them in the autocomplete
    "labels",                       // Allow users to tag documents with labels
    "alerts",                       // Allow users to subscribe to a regular alert for a particular query
    "suggests",                     // Display general text suggestions in the autocomplete
    "advanced-form",                // Display an advanced search form
    "keep-advanced-form-filters",   // When the user makes a new search query, do not reset the content of the autocomplete form
    "keep-tab",                     // When the user makes a new search query, stay on the same tab
    //"keep-filters",                 // When the user makes a new search query, do not reset the filters that are active (eg. from facets)
    "toggle-keep-filters",          // Display a button to toggle the "keep-filter" option
    //"voice-recognition",            // Display a button to trigger voice recognition (supported only on Chrome-based browsers and uses Google servers for processing)
];

export const FACETS: FacetConfig[] = [
    {
        name: "geo",
        title: "msg#facet.geo.title",
        type: "list",
        aggregation: "Geo",
        icon: "fas fa-globe-americas",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "company",
        title: "msg#facet.company.title",
        type: "list",
        aggregation: "Company",
        icon: "fas fa-building",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "person",
        title: "msg#facet.person.title",
        type: "list",
        aggregation: "Person",
        icon: "fas fa-user",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "docformat",
        title: "msg#facet.docformat.title",
        type: "list",
        aggregation: "DocFormat",
        icon: "far fa-file-word",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "modified",
        title: "msg#facet.modified.title",
        type: "list",
        aggregation: "Modified",
        icon: "fas fa-calendar-day",
        showCount: true,
        searchable: false,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "size",
        title: "msg#facet.size.title",
        type: "list",
        aggregation: "Size",
        icon: "fas fa-sort-amount-up-alt",
        showCount: true,
        searchable: false,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },

    {
        name: "concepts",
        title: "msg#facet.concepts.title",
        type: "list",
        aggregation: "Concepts",
        icon: "fas fa-comment-dots",
        showCount: true,
        searchable: false,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "PMID",
        title: "PMID",
        type: "list",
        aggregation: "PMID",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "Title",
        title: "Title",
        type: "list",
        aggregation: "Title",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
  
    {
        name: "ArticleId",
        title: "ArticleId",
        type: "list",
        aggregation: "ArticleId",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "Author",
        title: "Author",
        type: "list",
        aggregation: "Author",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "Status",
        title: "Status",
        type: "list",
        aggregation: "Status",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "JournalTitle",
        title: "JournalTitle",
        type: "list",
        aggregation: "JournalTitle",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "Language",
        title: "Language",
        type: "list",
        aggregation: "Language",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "Country",
        title: "Country",
        type: "list",
        aggregation: "Country",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
     {
        name: "Heatmap",
        title: "Heatmap",
        type: "list",
        aggregation: "Heatmap",
        icon: "fas fa-sort-amount-up-alt",
        showCount: true,
        searchable: false,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "PublishedDate",
        title: "PublishedDate",
        type: "list",
        aggregation: "PublishedDate",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "RegistryNumber",
        title: "RegistryNumber",
        type: "list",
        aggregation: "RegistryNumber",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "PublicationStatus",
        title: "PublicationStatus",
        type: "list",
        aggregation: "PublicationStatus",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
{
         name: "Disease",
        title: "Disease",
        type: "list",
        aggregation: "Disease",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
 
    },
    {
         name: "Drug",
        title: "Drug",
        type: "list",
        aggregation: "Drug",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
 
    },
    

     {
        name: "ISSNType",
        title: "ISSNType",
        type: "list",
        aggregation: "ISSNType",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
        name: "DOI",
        title: "DOI",
        type: "list",
        aggregation: "DOI",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
        
     {
        name: "KeywordsList",
        title: "KeywordsList",
        type: "list",
        aggregation: "KeywordsList",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
  
    {
        name: "AffiliationInfo",
        title: "AffiliationInfo",
        type: "list",
        aggregation: "AffiliationInfo",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
    },
    {
         name: "Timeline",
        title: "Timeline",
        type: "list",
        aggregation: "Timeline",
        showCount: true,
        searchable: true,
        allowExclude: true,
        allowOr: true,
        allowAnd: false,
        displayEmptyDistributionIntervals: false,
 
    },
    
];

export const METADATA: string[] = [
    "docformat", "modified", "size", "treepath", "filename","PMID", "Title","JournalTitle","ArticleId","ArticleTitle","Author", 
    "Language","PublicationType","PublicationStatus","ISSNType","RegistryNumber","Status","Owner","Country","DOI","KeywordsList","AffiliationInfo","ReferenceList","Pubmed","pii","Pmc"
    
];
